#!/bin/sh
#
# Start emulation station
#

case "$1" in
  start)
	echo -n "Starting emulation station: "
	export SDL_NOMOUSE=1
	export HOME=/root/
	start-stop-daemon -b -S -m -p /var/run/emulationstation.pid --exec /usr/bin/emulationstation -- -n
	echo "OK"
	;;
  stop)
	echo -n "Stopping emulation station: "
	start-stop-daemon -K -q -p /var/run/emulationstation.pid
	echo "OK"
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
